# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn build
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: build/


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: deploy
      uses: actions/download-artifact@v1
      with:
        name: dist

    - run: ls dist
